apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  replicas: 1 
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:3.7.0
        ports:
        - containerPort: 9092
        env:
        # Cú pháp của bản gốc Apache sẽ bỏ chữ "CFG_" đi
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://98.84.11.81:9092"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:9093"
        # Bản gốc yêu cầu bắt buộc phải cấp một ID cụm
        - name: CLUSTER_ID
          value: "kraft-cluster-id-123456" 
        resources:
          requests:
            memory: "512Mi" 
            cpu: "250m"
          limits:
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  type: LoadBalancer 
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka